CREATE TABLE vehicle_data (
    accident_index TEXT,
    accident_year INTEGER,
    accident_reference TEXT,
    vehicle_reference INTEGER,
    vehicle_type INTEGER,
    towing_and_articulation INTEGER,
    vehicle_manoeuvre INTEGER,
    vehicle_direction_from INTEGER,
    vehicle_direction_to INTEGER,
    vehicle_location_restricted_lane INTEGER,
    junction_location INTEGER,
    skidding_and_overturning INTEGER,
    hit_object_in_carriageway INTEGER,
    vehicle_leaving_carriageway INTEGER,
    hit_object_off_carriageway INTEGER,
    first_point_of_impact INTEGER,
    vehicle_left_hand_drive INTEGER,
    journey_purpose_of_driver INTEGER,
    sex_of_driver INTEGER,
    age_of_driver INTEGER,
    age_band_of_driver INTEGER,
    engine_capacity_cc INTEGER,
    propulsion_code INTEGER,
    age_of_vehicle INTEGER,
    generic_make_model TEXT,
    driver_imd_decile INTEGER,
    driver_home_area_type INTEGER,
    lsoa_of_driver TEXT,
    escooter_flag INTEGER,
    dir_from_e DOUBLE PRECISION,
    dir_from_n DOUBLE PRECISION,
    dir_to_e DOUBLE PRECISION,
    dir_to_n DOUBLE PRECISION,
    driver_distance_banding INTEGER
);